Flask_Tutorial/tutorial3/project/home/forms.py
from flask_wtf import Form
from wtforms import TextField 
from wtforms.validators import DataRequired, Length

class MessageForm(Form):
	title = TextField('Title', validators=[DataRequired()])
	description = TextField('Description', validators=[DataRequired(), Length(max=40)])



Flask_Tutorial/tutorial3/project/home/views.py
from project import app, db
from project.models import BlogPost
from flask import  render_template, url_for, redirect,  url_for, request,  flash, Blueprint
from functools import wraps
from flask_login import login_required, current_user
from .forms import MessageForm

home_blueprint = Blueprint(
	'home', __name__,
	template_folder='templates'
)

# def login_required(test):
# 	@wraps(test)
# 	def warp(*args, **kwargs):
# 		if 'logged_in' in session:
# 			return test(*args, **kwargs)
# 		else:
# 			flash ('@Loing_required You need to login  first.')
# 			return  redirect(url_for('users.login'))
# 	return warp



# @home_blueprint.route("/")
# @login_required
# def home():
# 		posts = db.session.query(BlogPost).all()
# 		return render_template("index.html", posts=posts)



@home_blueprint.route('/', methods=['GET','POST'])
@login_required
def home():
	error = None
	form = MessageForm(request.form)

	if form.validate_on_submit():
		new_message = BlogPost(
			form.title.data,
			form.description.data,
			current_user.id
			)
		db.session.add(new_message)
		db.session.commit()
		flash('New entry was successfully posted. Thank.')
		return redirect(url_for('home.home'))
	else:
		posts  = db.session.query(BlogPost).all()
		return render_template("index.html", posts=posts, form=form, error=error)


@home_blueprint.route('/welcome')
#@login_required
def welcome():
	return render_template('welcome.html')


# @app.route('/logout')
# @login_required
# def logout():
# 	session.pop('logined_in',None)
# 	flash('You ware just logged out!!')
# 	return  redirect(url_for('welcome'))

Flask_Tutorial/tutorial3/project/users/views.py
from  flask import flash, redirect, render_template, request, \
	  url_for, Blueprint
#from functools  import wraps

from .forms  import LoginForm, RegisterForm
from project.models import User, bcrypt
from flask_login import login_user, login_required, logout_user
from project import  db


#from project  import  bcrypt



users_blueprint = Blueprint( 
	'users', __name__,
	 template_folder='templates'
	)


# def login_required(test):
# 	@wraps(test)
# 	def wrap(*args, **kwargs):
# 		if 'logged_in' in session:
# 			return test(*args, **kwargs)
# 		else:
# 			flash ('You need to login frist!!')
# 			return redirect(url_for('users.login'))
# 	return wrap

###############
#### routes ###
###############



# @users_blueprint.route('/login',methods=['GET','POST'])
# def login():
# 	error = None
# 	if request.method == 'POST':
# 		if (request.form['username'] != 'admin') or \
# 			 (request.form['password']  != 'admin'):
# 			error = 'Invalid credentials Plases try again.'
# 			print request.form['username']
# 		else:
# 			session['logged_in'] = True
# 			flash('You were logged in.')
# 			return redirect(url_for('home'))
# 	return render_template('login.html', error=error)



@users_blueprint.route('/login', methods=['GET', 'POST'])

def login():
	error = None
	form = LoginForm(request.form)

	if request.method ==  'POST':
		if form.validate_on_submit():
		 	user = User.query.filter_by(name=request.form['username']).first()
		 	if user is not None and bcrypt.check_password_hash(user.password,request.form['password'] ):
			# if request.form['username'] != 'admin' or  request.form['password'] != 'admin':
			# 	error = 'Invalid credentials Plases try again.'
			# 	print request.form['username']
			# else:
			#	session['logined_in'] = True
				login_user(user)
				flash('You are login Success!!')
				return redirect(url_for('home.home'))
			else:
				error = "Invalid credentials Plases try again."
		else:
			return render_template("login.html",form=form, error=error)
					
	return render_template("login.html",form=form, error=error)


@users_blueprint.route('/logout')
@login_required

def logout():
	#session.pop('logged_in', None)
	logout_user()
	#session.clear()
	flash('You were logged out')
	return redirect(url_for('home.welcome'))

@users_blueprint.route('/register/', methods=['GET','POST'])
def register():
	form  = RegisterForm()
	if form.validate_on_submit():
		user = User(
			 name = form.username.data,
			 email = form.email.data,
			 password = form.password.data
			 )
		db.session.add(user)
		db.session.commit()
		login_user(user)
		return redirect(url_for('home.home'))
	return render_template('register.html', form=form)

Flask_Tutorial/tutorial3/project/home/templates/index.html
{% extends "base.html" %}

{% block __content__ %}
      <div class="starter-template">
      <!-- 
        <h1>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.
        <br> Click <a href="{{ url_for('users.logout') }}"> here </a> to Logout. </p>
      -->

      <h3> Welcome to Flask! </h3>
   
      	{%  for post in posts %}
   
      	<strong>Title:</strong> {{ post.title }} <br>
      	<strong>Post: </strong> {{ post.description }} <br>
        <strong>Author: </strong> {{ post.author.name }} <br>
      	{% endfor %}

	</div> <!--end starter-template -->

	  <br> Click <a href="{{ url_for('users.logout') }}"> here </a> to Logout. </p>
      {% for  message in get_flashed_messages() %}
        {{ message }}
      {% endfor %}
{% endblock %}

{% block content %}

<h1>Welcome to Flask!</h1>
<br>
<p>Click <a href="/logout">here</a> to logout.</p>
<br>

<!-- post form -->
<h3>Add a Post!</h3>
<br>
<form class="form-message" role="form" method="post" action="/">
  {{ form.csrf_token }}
  <p>
    {{ form.title(placeholder="title") }}
    <span class="error">
      {% if form.title.errors %}
        {% for error in form.title.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.description(placeholder="description") }}
    <span class="error">
      {% if form.description.errors %}
        {% for error in form.description.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button class="btn btn-sm btn-success" type="submit">Post</button>
</form>

<!-- All posts -->
<h3>Posts:</h3>
{% for post in posts %}
  <strong>Title:</strong> {{ post.title }} <br>
  <strong>Post:</strong> {{ post.description }} <br>
  <strong>Author:</strong> {{ post.author.name }} <br>
<br>
{% endfor %}

{% endblock %}

Flask_Tutorial/tutorial3/project/home/templates/welcome.html
{% extends "base.html" %}
{% block content %}

      <div class="starter-template">
        <h1> Welcome to  Flask!! </h1>
        <p class="lead">
             Hello My World !!
          click <a href="{{ url_for('home.home' ) }}"> here </a> to Home.</p>
      </div>

      {% for  message in get_flashed_messages() %}
        {{ message }}
      {% endfor %}

{% endblock %}